// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "enable": boolean;
      "input": string;
      "apiBase": string;
      "apiKey": string;
      "model": string;
      "modelProviderGroups": string;
      "modelProviderGroupsMigrationVersion": number;
      "lastUsedModelEntryId": string;
      "systemPrompt": string;
      "showPopupAddText": boolean;
      "scrollSectionIntoViewOnSwitch": boolean;
      "semanticScholarApiKey": string;
      "temperaturePrimary": string;
      "maxTokensPrimary": string;
      "temperatureSecondary": string;
      "maxTokensSecondary": string;
      "temperatureTertiary": string;
      "maxTokensTertiary": string;
      "temperatureQuaternary": string;
      "maxTokensQuaternary": string;
      "enableAgentMode": boolean;
      "agentBackendMode": string;
      "agentBackendBridgeUrl": string;
      "agentBackendAutoSpawn": boolean;
      "agentBackendAdapterPath": string;
      "agentClaudeTerminalPath": string;
      "obsidianVaultPath": string;
      "obsidianTargetFolder": string;
      "obsidianAttachmentsFolder": string;
      "obsidianNoteTemplate": string;
      "notesDirectoryNickname": string;
      "locale": string;
      "mineruMode": string;
      "mineruLocalApiBase": string;
      "mineruLocalBackend": string;
      "mineruAutoWatchCollections": string;
      "mineruGlobalAutoParse": boolean;
      "mineruSyncEnabled": boolean;
      "mineruExcludePatterns": string;
    };
  }
}
